export type {
	FileManager,
	CreateFolderOptions,
	CreateTextFileOptions,
	FolderChild,
	EntryWithXattrs,
	FolderWithChildrenXattrs,
	Xattr,
	MediaSrc,
	MediaVariant,
	UploadProgressCallback,
	PutBlob,
	WatchEvent,
	WatchEventKind,
	Unwatch,
	FolderStroke,
	StrokesWatchEvent,
	FolderStrokesStore,
	ConnectionHandle,
	ConnectionMarker,
	FolderConnection,
	ConnectionsWatchEvent,
	FolderConnectionsStore,
} from './types'
export { createFileManager, type FileManagerType } from './factory'
export { default as createMockFileManager, type MockFileManagerOptions } from './mock'
export { createFakeFileManager, type FakeFileManager, type FakeEntrySnapshot } from './fake'
export {
	createDemoFileManager,
	createDemoFileManagerFrom,
	demoContent,
	type DemoContent,
	type DemoContentEntry,
} from './demo'
export {
	PILE_ATTRS_VERSION,
	PILE_DIR_NAME,
	PILE_ATTRS_FILE,
	STROKES_ATTR,
	CANVAS_ATTR,
	parsePileAttrsManifest,
	serializePileAttrsManifest,
	parse_packed_strokes,
	parse_packed_connections,
	collectPileAttrs,
	applyPileAttrs,
	type PileAttrsManifest,
	type ApplyPileAttrsResult,
	type ApplyPileAttrsOptions,
} from './pile-attrs'
export { resolve_connection_endpoint } from './connectionPaths'
export {
	default as createCloudFileManager,
	create_workspace,
	add_workspace_member,
	preview_workspace_invite,
	claim_workspace_invites,
	list_workspace_members,
	get_workspace_access,
	get_published_workspace,
	get_profile_by_username,
	get_my_profile,
	update_profile,
	list_user_publications,
	list_hub_publications,
	list_hub_authors,
	list_hub_tags,
	set_hub_listing,
	remove_from_hub,
	report_hub_listing,
	hub_listing_reported,
	restore_entry,
	purge_entry,
	purge_trash,
	list_trash,
	workspace_usage,
	set_workspace_public,
	set_workspace_private,
	fork_workspace,
	mime_from_name,
	is_text_mime,
	inert_document_mime,
	MAX_TEXT_CONTENT_BYTES,
	first_embed,
	owner_usage,
	get_billing_account,
	record_quota_wall_event,
	update_quota_wall_event,
	get_plan_limits,
	record_bridge_event,
	retry_after_ms,
	type CloudFileManagerOptions,
	type EntryRow,
	type TrashEntry,
	type WorkspaceUsage,
	type OwnerUsage,
	type BillingAccount,
	type QuotaWallEventInput,
	type PlanLimits,
	type BridgeEventInput,
	type WorkspaceRole,
	type WorkspaceMember,
	type WorkspaceInvite,
	type WorkspaceInvitePreview,
	type AddWorkspaceMemberResult,
	type WorkspaceAccess,
	type PublishedWorkspace,
	type Profile,
	type UserPublication,
	type HubPublication,
	type HubAuthor,
	type HubTag,
	type HubPage,
	type HubListOptions,
	HUB_PAGE_SIZE,
} from './supabase'
export {
	parse_plan_limit_error,
	PlanLimitError,
	throw_if_plan_limit,
	type PlanLimitKind,
	type PlanLimitInfo,
} from './planLimit'
export {
	MediaUnavailableError,
	parse_media_unavailable,
	type MediaUnavailableReason,
} from './mediaUnavailable'
export { StorageUnreachableError } from './storageUnreachable'
export {
	HUB_PREVIEW_ACCEPT,
	HUB_PREVIEW_KEY_RE,
	HUB_PREVIEW_MAX_BYTES,
	hub_preview_ext,
	hub_preview_file_error,
	hub_preview_url,
	is_hub_preview_key,
	upload_hub_preview,
} from './hubPreview'
export {
	createBrowserFileManager,
} from './browser/browser'
export { download_blob } from './browser/download'
export {
	browser_path_within,
	createMemoryBrowserStorage,
	type BrowserConnectionsDoc,
	type BrowserEntryRecord,
	type BrowserStorage,
	type BrowserStorageSnapshot,
	type BrowserStrokesDoc,
	type BrowserSubtreeWrite,
} from './browser/storage'
export { createIdbBrowserStorage } from './browser/idbStorage'
export {
	ABUSE_EMAIL,
	abuse_mailto,
} from './abuse'
export {
	RESERVED_SLUGS,
	SLUG_PATTERN,
	is_reserved_slug,
	is_valid_slug,
} from './reserved-slugs'
export {
	APP_DESCRIPTION,
	APP_TITLE,
	HUB_DESCRIPTION,
	HUB_TITLE,
	apply_unfurl,
	build_unfurl_meta,
	inject_unfurl_tags,
	load_unfurl_data,
	unfurl_cache_control,
	unfurl_path,
	unfurl_pathname_from_query,
	unfurl_route,
	unfurl_title,
	type UnfurlCache,
	type UnfurlMeta,
	type UnfurlPageData,
	type UnfurlRoute,
	type UnfurlUrls,
} from './unfurl'

